# -*- coding: utf-8 -*-
"""Remove_duplication.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1swMtfkBqNB4Srj6DcuQqniX8WWeU6NBj
"""

import pandas as pd

data = pd.read_csv("Iris.csv")

data

data.head()

data.duplicated()

data.duplicated().sum()

data['Species'].duplicated()

data['Species'].duplicated().sum()

data[data['Species'].duplicated()].head(2)

data[data['Species'].duplicated(keep = 'last')].head(2)

data.shape

data['Species'].shape

data['Species'].drop_duplicates()

data['Species'].drop_duplicates().shape

data.drop_duplicates(subset=['SepalLengthCm' ,	'SepalWidthCm' ,	'PetalLengthCm'	,'PetalWidthCm' ,	'Species'])

